# Generated by Django 3.2.7 on 2021-09-04 13:36

import News.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to=News.models.upload_to)),
                ('title', models.TextField(max_length=100, null=True)),
                ('data', models.DateTimeField(auto_now=True)),
                ('short_text', models.CharField(max_length=1000)),
                ('text', models.TextField()),
                ('newslink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=News.models.upload_to)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='News.news')),
            ],
        ),
    ]
