# Generated by Django 3.2.7 on 2021-09-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename_image1_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlecurrent', models.TextField(max_length=100, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DraftLegulatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleLegulatory', models.TextField(max_length=100, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DraftRegulatoryLegalActs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draftregulatorylegalacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.draftlegulatory')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLegislature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentlegislature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.current')),
            ],
        ),
    ]
