# Generated by Django 3.2.7 on 2021-09-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_current_currentlegislature_draftlegulatory_draftregulatorylegalacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titledocs', models.TextField(max_length=100, null=True, verbose_name='Заголовок документа')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Международные документы',
            },
        ),
        migrations.CreateModel(
            name='LegislationNKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, null=True, verbose_name='Вводный текст о разделе')),
            ],
        ),
        migrations.RemoveField(
            model_name='draftregulatorylegalacts',
            name='draftregulatorylegalacts',
        ),
        migrations.AlterModelOptions(
            name='current',
            options={'verbose_name': 'Законодательство'},
        ),
        migrations.AlterModelOptions(
            name='draftlegulatory',
            options={'verbose_name': 'Правовые акты'},
        ),
        migrations.RemoveField(
            model_name='draftlegulatory',
            name='titleLegulatory',
        ),
        migrations.AddField(
            model_name='draftlegulatory',
            name='titlelegulatory',
            field=models.TextField(max_length=100, null=True, verbose_name='Заголовок актов'),
        ),
        migrations.AlterField(
            model_name='current',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='current',
            name='titlecurrent',
            field=models.TextField(max_length=100, null=True, verbose_name='Законодательство'),
        ),
        migrations.AlterField(
            model_name='draftlegulatory',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.DeleteModel(
            name='CurrentLegislature',
        ),
        migrations.DeleteModel(
            name='DraftRegulatoryLegalActs',
        ),
        migrations.AddField(
            model_name='legislationnko',
            name='Current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.current'),
        ),
        migrations.AddField(
            model_name='legislationnko',
            name='DraftLegulatory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.draftlegulatory'),
        ),
        migrations.AddField(
            model_name='legislationnko',
            name='InternationalDocuments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.internationaldocuments'),
        ),
    ]
