# Generated by Django 3.2.7 on 2021-09-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20210905_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftlegulatory',
            name='titlelegulatory',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок актов'),
        ),
    ]
