# Generated by Django 3.2.7 on 2021-09-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_alter_draftlegulatory_titlelegulatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='titlecurrent',
            field=models.CharField(max_length=100, null=True, verbose_name='Законодательство'),
        ),
        migrations.AlterField(
            model_name='internationaldocuments',
            name='titledocs',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок документа'),
        ),
        migrations.AlterField(
            model_name='legislationnko',
            name='text',
            field=models.CharField(max_length=1000, null=True, verbose_name='Вводный текст о разделе'),
        ),
    ]
