# Generated by Django 3.2.7 on 2021-09-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20210906_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legislationnko',
            old_name='Current',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='legislationnko',
            old_name='DraftLegulatory',
            new_name='draftlegulatory',
        ),
        migrations.RenameField(
            model_name='legislationnko',
            old_name='InternationalDocuments',
            new_name='internationaldocuments',
        ),
    ]
