# Generated by Django 3.2.7 on 2021-09-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_auto_20210906_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislationnko',
            options={'verbose_name': 'Законодательство НКО'},
        ),
    ]
