# Generated by Django 3.2.7 on 2021-09-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_alter_legislationnko_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название законодательство')),
            ],
        ),
        migrations.RemoveField(
            model_name='legislationnko',
            name='current',
        ),
        migrations.RemoveField(
            model_name='legislationnko',
            name='draftlegulatory',
        ),
        migrations.RemoveField(
            model_name='legislationnko',
            name='internationaldocuments',
        ),
        migrations.DeleteModel(
            name='Current',
        ),
        migrations.DeleteModel(
            name='DraftLegulatory',
        ),
        migrations.DeleteModel(
            name='InternationalDocuments',
        ),
        migrations.AddField(
            model_name='legislationnko',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='News.ncocategory'),
        ),
    ]
