# Generated by Django 3.2.7 on 2021-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20210906_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncocategory',
            options={'verbose_name': 'Законодательство об НКО'},
        ),
        migrations.AddField(
            model_name='legislationnko',
            name='all_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='legislationnko',
            name='text',
            field=models.CharField(max_length=1000, null=True, verbose_name='Название закона'),
        ),
    ]
