# Generated by Django 3.2.7 on 2021-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_auto_20210906_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislationnko',
            options={'verbose_name': 'Законы'},
        ),
        migrations.RenameField(
            model_name='legislationnko',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='legislationnko',
            name='all_text',
            field=models.TextField(null=True, verbose_name='Описание закона'),
        ),
    ]
