# Generated by Django 3.2.7 on 2021-09-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0014_ncolibrarycategory_publicationsnko'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Избранное Новостей'},
        ),
        migrations.AlterModelOptions(
            name='imagenews',
            options={'verbose_name': 'Изображение для новости'},
        ),
        migrations.AlterModelOptions(
            name='legisfavourite',
            options={'verbose_name': 'Избранное законов '},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости'},
        ),
    ]
