# Generated by Django 3.2.7 on 2021-09-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0016_auto_20210910_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationsnko',
            name='name',
        ),
        migrations.DeleteModel(
            name='NCOLibraryCategory',
        ),
        migrations.DeleteModel(
            name='PublicationsNKO',
        ),
    ]
