# Generated by Django 3.2.7 on 2021-09-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryNKO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ncolibrarycategory',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='publicationsnko',
            old_name='name',
            new_name='category',
        ),
    ]
