# Generated by Django 3.2.7 on 2021-09-10 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NCOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название законодательство')),
            ],
            options={
                'verbose_name': 'Законодательство об НКО',
            },
        ),
        migrations.CreateModel(
            name='LegislationNKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True, verbose_name='Название закона')),
                ('all_text', models.TextField(null=True, verbose_name='Описание закона')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Legis.ncocategory')),
            ],
            options={
                'verbose_name': 'Законы',
            },
        ),
        migrations.CreateModel(
            name='LegisFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Legis.legislationnko')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное законов ',
            },
        ),
    ]
