# Generated by Django 3.2.7 on 2021-09-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legis', '0002_auto_20210913_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='law',
            old_name='type',
            new_name='type_id',
        ),
    ]
