# Generated by Django 3.2.7 on 2021-09-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Legis', '0003_rename_type_law_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название законодательство')),
            ],
            options={
                'verbose_name': 'Законодательство об НКО',
            },
        ),
        migrations.CreateModel(
            name='LawAllNKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True, verbose_name='Название закона')),
                ('all_text', models.TextField(null=True, verbose_name='Описание закона')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Legis.ncocategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Законы',
            },
        ),
        migrations.AlterField(
            model_name='legisfavourite',
            name='legis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Legis.lawallnko'),
        ),
        migrations.DeleteModel(
            name='Law',
        ),
    ]
