# Generated by Django 3.2.7 on 2021-09-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legis', '0004_auto_20210915_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawallnko',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ncocategory',
            old_name='name',
            new_name='category',
        ),
    ]
